# Generated by Django 4.2.30 on 2026-05-06 00:00

from django.db import migrations


def create_default_sitesetup(apps, schema_editor):
    SiteSetup = apps.get_model('site_setup', 'SiteSetup')

    SiteSetup.objects.get_or_create(
        title='Blog Django',
        defaults={
            'description': 'Bem-vindo ao blog',
            'show_header': True,
            'show_search': True,
            'show_menu': True,
            'show_description': True,
            'show_pagination': True,
            'show_footer': True,
            'favicon': '',
        }
    )


def delete_default_sitesetup(apps, schema_editor):
    SiteSetup = apps.get_model('site_setup', 'SiteSetup')

    SiteSetup.objects.filter(
        title='Blog Django',
        description='Bem-vindo ao blog'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_alter_menulink_site_setup_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.RunPython(create_default_sitesetup, delete_default_sitesetup),
    ]
